### PR TITLE
Allowing the user to specify the name of output file at make_stage

### PR DESCRIPTION
**Pull request by joselotl**

### CODE REVIEW

**Review by eacharles — COMMENTED** [review]
Looks good to me.   Only real question is if we want to add a test to the unit tests to explicitly test this case.  @joezuntz Do you have an opinion?

**Comment by joezuntz** [comment]
Probably a good idea to have a test, since we may be modifying this part of the code more as time goes on.

**Comment by eacharles** [comment]
Ok, @joselotl can you  modify one of the tests in the `tests` area to including  changing the otuput filename and make sure that the new line of code gets executed.

**Comment by joselotl** [comment]
I included the test. And it's not working! Somehow the stage in the test doesn't change its default output. Unlike the rail stage where I tested my solution and it worked. Maybe I'll have to think in a different solution.

**Comment by eacharles** [comment]
Interesting.   Note that I put some additional functionality in the rail specific sub-class in`rail.core.stage`.   It could easily be that some of the stuff that this needs to work is actually in there.   I think we should get together with Joe Z. and talk this through at some point.

**Comment by joezuntz** [comment]
This looks good - I'm happy to merge if it's ready.

**Pull request merged**
